### ISSUE TITLE
npm install colorthief not working anymore

### ISSUE THREAD

**Issue by odebroqueville** [lokesh/color-thief#217]
Not sure what to make of this! Is colorthief using node-pre-gyp as a dependency? If so, [this might help](https://github.com/node-webrtc/node-webrtc/issues/682).

```
contextSearch % npm install color-thief
Debugger attached.
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm ERR! code 1
npm ERR! path /Users/odebroqueville/Developer/contextSearch/node_modules/canvas
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! Failed to execute '/Users/odebroqueville/.nvm/versions/node/v17.3.0/bin/node /Users/odebroqueville/.nvm/versions/node/v17.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/odebroqueville/Developer/contextSearch/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/odebroqueville/Developer/contextSearch/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v102' (1)
npm ERR! Debugger attached.
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.11.0
npm ERR! node-pre-gyp info using node@17.3.0 | darwin | x64
npm ERR! node-pre-gyp WARN Using needle for node-pre-gyp https download 
npm ERR! node-pre-gyp info check checked for "/Users/odebroqueville/Developer/contextSearch/node_modules/canvas/build/Release/canvas.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.5.0/canvas-v2.5.0-node-v102-darwin-unknown-x64.tar.gz
npm ERR! node-pre-gyp http 404 https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.5.0/canvas-v2.5.0-node-v102-darwin-unknown-x64.tar.gz
npm ERR! node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.5.0/canvas-v2.5.0-node-v102-darwin-unknown-x64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not found for canvas@2.5.0 and node@17.3.0 (node-v102 ABI, unknown) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp http 404 status code downloading tarball https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.5.0/canvas-v2.5.0-node-v102-darwin-unknown-x64.tar.gz 
npm ERR! Debugger attached.
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@17.3.0 | darwin | x64
npm ERR! gyp info ok 
npm ERR! Waiting for the debugger to disconnect...
npm ERR! Debugger attached.
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@17.3.0 | darwin | x64
npm ERR! gyp info find Python using Python version 3.8.9 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
npm ERR! gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/odebroqueville/.nvm/versions/node/v17.3.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/odebroqueville/Developer/contextSearch/node_modules/canvas/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/odebroqueville/.nvm/versions/node/v17.3.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/odebroqueville/Library/Caches/node-gyp/17.3.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/odebroqueville/Library/Caches/node-gyp/17.3.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/odebroqueville/.nvm/versions/node/v17.3.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/odebroqueville/Library/Caches/node-gyp/17.3.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/odebroqueville/Developer/contextSearch/node_modules/canvas',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Debugger attached.
npm ERR! Waiting for the debugger to disconnect...
npm ERR! gyp: Call to 'node ./util/has_lib.js jpeg' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/Users/odebroqueville/.nvm/versions/node/v17.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:259:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 21.2.0
npm ERR! gyp ERR! command "/Users/odebroqueville/.nvm/versions/node/v17.3.0/bin/node" "/Users/odebroqueville/.nvm/versions/node/v17.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/odebroqueville/Developer/contextSearch/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/Users/odebroqueville/Developer/contextSearch/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v102"
npm ERR! gyp ERR! cwd /Users/odebroqueville/Developer/contextSearch/node_modules/canvas
npm ERR! gyp ERR! node -v v17.3.0
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok 
npm ERR! Waiting for the debugger to disconnect...
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/Users/odebroqueville/.nvm/versions/node/v17.3.0/bin/node /Users/odebroqueville/.nvm/versions/node/v17.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/odebroqueville/Developer/contextSearch/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/odebroqueville/Developer/contextSearch/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v102' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/odebroqueville/Developer/contextSearch/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1062:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! node-pre-gyp ERR! System Darwin 21.2.0
npm ERR! node-pre-gyp ERR! command "/Users/odebroqueville/.nvm/versions/node/v17.3.0/bin/node" "/Users/odebroqueville/Developer/contextSearch/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /Users/odebroqueville/Developer/contextSearch/node_modules/canvas
npm ERR! node-pre-gyp ERR! node -v v17.3.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.11.0
npm ERR! node-pre-gyp ERR! not ok 
npm ERR! Waiting for the debugger to disconnect...
```

**Comment by rweilg** [comment]
Downgrading NPM to 7.24.0 and Node to 14.15.4 fixed the problem for me

**Comment by quiquelhappy** [comment]
anyone can link any alternative for this package on npmjs? this repo seems to be abandoned, this has been an ongoing issue for months now.

**Comment by pioug** [comment]
@quiquelhappy Hello, I created a monorepo with `colorthief` including some (abandoned) dependencies that needed an update too https://github.com/pioug/colorsuite

```
npm install colorthief@npm:@pioug/colorthief
```

**Comment by kevinlens** [comment]
> @quiquelhappy Hello, I created a monorepo with `colorthief` including some (abandoned) dependencies that needed an update too https://github.com/pioug/colorsuite
> 
> ```
> npm install colorthief@npm:@pioug/colorthief
> ```
> 
> Tell me if you'd like to be added as a maintainer to keep the project alive 👍

please include more documentation on how to use it. There are too many errors trying to using this thing

**Comment by lokesh** [comment]
The latest release of color-thief (v2.4.0) updates the quantize dependency reference in package.json and this should resolve any install issues:
https://github.com/lokesh/color-thief/releases/

Sorry for the headaches.

**Comment by victorcngo** [comment]
> The latest release of color-thief (v2.4.0) updates the quantize dependency reference in package.json and this should resolve any install issues: https://github.com/lokesh/color-thief/releases/
> 
> Sorry for the headaches.

hi @lokesh! thanks for sharing this. can you please tell me how should i proceed to install this and use it?
